<?php

use Drupal\Core\Routing\RouteMatchInterface;

function honeys_place_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.honeys_place':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t(
                    'Add the field_honey_order_created field to any/all order types you want to use.
        Then configure your API credentials on the below configuration page.') . '</p>';
            return $output;

        default:
    }
}
function honeys_place_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() === 'commerce_order') {
    $order = \Drupal\commerce_order\Entity\Order::load($entity->id());
    echo '<pre>';
    echo 'test';
    foreach ($order->getItems() as $item) {
	    echo $item->getPurchasedEntity()->get('sku')->value;
	    echo '<p>'.$item->getQuantity().'</p>';
	    //print_r(array_keys($item->getPurchasedEntity()->get('sku')));
    }
    print_r(array_keys($order->get('order_items')));
    echo '</pre>';
  }
}

function honeys_place_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id !== 'commerce_order_default_edit_form') {
    return;
  }       
	echo '<pre>';
  //var_dump($form['order_items']['widget']['entities'][0]);
  echo '</pre>';
}
