name: Menu link config
type: module
description: 'Allows to create menu links as config'
package: Menu
core: 8.x
core_version_requirement: ^8 || ^9

# Information added by Drupal.org packaging script on 2021-08-13
version: '8.x-1.0-alpha3'
project: 'menu_link_config'
datestamp: 1628872511
