<?php

use Drupal\Core\Routing\RouteMatchInterface;

function honeys_place_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.honeys_place':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t(
                    'Add the field_honey_order_created field to any/all order types you want to use.
        Then configure your API credentials on the below configuration page.') . '</p>';
            return $output;

        default:
    }
}

/**
* Implements hook_mail().
*/
function honeys_place_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );

 switch ($key) {
   case 'OrderTrackNumber':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t($params['subject'], $options);
     $message['body'][] = $params['message'];
	 $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
     break;
 }
}